package io.github.vgy789.doorDuck.shared

import io.github.vgy789.doorDuck.model.Defaults
import io.github.vgy789.doorDuck.model.ConnectionCheckResult
import io.github.vgy789.doorDuck.model.SyncError

internal data class SharedStrings(
    val loading: String,
    val appTitle: String,
    val appSubtitle: String,
    val wizardTitle: String,
    val welcomeTitle: String,
    val welcomeBody: String,
    val credentialsTitle: String,
    val credentialsHint: String,
    val endpointTitle: String,
    val connectionHint: String,
    val doneTitle: String,
    val doneBody: String,
    val homeTitle: String,
    val homeSubtitle: String,
    val settingsTitle: String,
    val endpointLabel: String,
    val userIdLabel: String,
    val tokenLabel: String,
    val actionStart: String,
    val actionNext: String,
    val actionFinish: String,
    val actionOpenApp: String,
    val actionOpenSettings: String,
    val actionCheckConnection: String,
    val actionShowEndpointSettings: String,
    val actionHideEndpointSettings: String,
    val endpointPresetBase: String,
    val endpointPresetIntensive: String,
    val endpointPresetCustom: String,
    val intensiveCampusMoscow: String,
    val intensiveCampusNovosibirsk: String,
    val intensiveCampusKazan: String,
    val intensiveCampusOther: String,
    val endpointOtherCampusPlaceholder: String,
    val endpointCustomHint: String,
    val endpointViewBrowserExample: String,
    val endpointViewMobileExample: String,
    val actionRefreshNow: String,
    val actionSave: String,
    val actionClearSaved: String,
    val actionShowToken: String,
    val actionHideToken: String,
    val connectionChecking: String,
    val errorEndpointHttps: String,
    val errorTokenRequired: String,
    val errorUserIdRequired: String,
    val errorConnectionCheckRequired: String,
    val infoSettingsSaved: String,
    val infoWizardDone: String,
    val infoQrRefreshed: String,
    val infoRefreshShortCooldown: String,
    val statusFreshHeadline: String,
    val statusRefreshingHeadline: String,
    val statusNeedsRefreshHeadline: String,
    val statusMissingHeadline: String,
    val statusTitle: String,
    val statusStored: String,
    val statusRefreshInProgress: String,
    val statusLastError: String,
    val statusLastCheck: String,
    val statusExpiresAt: String,
    val statusConnection: String,
    val statusNotSet: String,
    val statusNever: String,
    val statusUnknown: String,
    val statusNone: String,
    val statusYes: String,
    val statusNo: String,
    val qrTitle: String,
    val qrEmpty: String,
    val connectionSectionTitle: String,
    val connectionSectionBody: String,
    val actionExpand: String,
    val actionCollapse: String,
    val widgetTitle: String,
    val widgetBody: String,
    val widgetAction: String,
    val widgetHelpMessage: String,
    val instructionTitle: String,
    val instructionBody: String,
    val instructionStep1: String,
    val instructionStep2: String,
    val instructionStep3: String,
    val instructionStep4: String,
    val instructionStep5: String,
    val instructionStep6: String,
    val instructionOpenLink: String,
    val instructionViewExample: String,
    val instructionHideExample: String,
    val instructionWebOnly: String,
    val githubLinkLabel: String,
    val githubOwnerLabel: String,
    val iosStatusTitle: String,
    val iosStatusBody: String,
    val tokensUrl: String,
    val githubUrl: String,
    val connectionOk: String,
    val connectionUnauthorized: String,
    val connectionBotNotFound: String,
    val connectionBotUnavailable: String,
    val connectionNetworkError: String,
    val connectionUnknownError: String,
    val syncErrorNotConfigured: String,
    val syncErrorUnauthorized: String,
    val syncErrorRateLimited: String,
    val syncErrorNetwork: String,
    val syncErrorBotInvalid: String,
    val syncErrorImageDownload: String,
    val syncErrorUnknown: String,
    val credentialsBlobLabel: String,
    val detectedCredentialsTitle: String,
    val detectedUserIdValue: String,
    val detectedTokenValue: String,
    val statusNotFound: String,
    val errorCredentialsBlobRequired: String,
) {
    fun connectionMessage(result: ConnectionCheckResult?): String {
        return when (result) {
            ConnectionCheckResult.SUCCESS -> connectionOk
            ConnectionCheckResult.UNAUTHORIZED -> connectionUnauthorized
            ConnectionCheckResult.BOT_NOT_FOUND -> connectionBotNotFound
            ConnectionCheckResult.BOT_UNAVAILABLE -> connectionBotUnavailable
            ConnectionCheckResult.NETWORK_ERROR -> connectionNetworkError
            ConnectionCheckResult.UNKNOWN, null -> connectionUnknownError
        }
    }

    fun syncErrorMessage(error: SyncError?): String {
        return when (error) {
            SyncError.NOT_CONFIGURED -> syncErrorNotConfigured
            SyncError.UNAUTHORIZED -> syncErrorUnauthorized
            SyncError.RATE_LIMITED -> syncErrorRateLimited
            SyncError.NETWORK -> syncErrorNetwork
            SyncError.BOT_NOT_FOUND -> connectionBotNotFound
            SyncError.BOT_RESPONSE_INVALID -> syncErrorBotInvalid
            SyncError.IMAGE_DOWNLOAD_FAILED -> syncErrorImageDownload
            SyncError.UNKNOWN, null -> syncErrorUnknown
        }
    }

    companion object {
        fun forLanguage(languageCode: String): SharedStrings {
            return if (languageCode.lowercase().startsWith("ru")) russian() else english()
        }

        private fun english() = SharedStrings(
            loading = "Loading doorDuck…",
            appTitle = "doorDuck for iOS",
            appSubtitle = "Setup, token verification, and manual QR refresh are available on iOS.",
            wizardTitle = "doorDuck Setup",
            welcomeTitle = "Welcome",
            welcomeBody = "Hi! I am doorDuck. I keep your campus QR widget active on the home screen.",
            credentialsTitle = "Paste token popup",
            credentialsHint = "Open the Rocket.Chat tokens page, create a new Personal Access Token, copy the full text from the popup, and paste it here.",
            endpointTitle = "Which endpoint do you need?",
            connectionHint = "Check connection with Rocket.Chat before finishing setup.",
            doneTitle = "Configuration complete",
            doneBody = "Settings are stored on this iPhone simulator. You can reopen the wizard later from settings.",
            homeTitle = "doorDuck",
            homeSubtitle = "Your current QR state and manual refresh controls.",
            settingsTitle = "doorDuck Settings",
            endpointLabel = "Rocket.Chat URL",
            userIdLabel = "Rocket.Chat user Id",
            tokenLabel = "X-Auth-Token",
            actionStart = "Start",
            actionNext = "Next",
            actionFinish = "Finish setup",
            actionOpenApp = "Open app",
            actionOpenSettings = "Open settings",
            actionCheckConnection = "Check connection",
            actionShowEndpointSettings = "Show endpoint settings",
            actionHideEndpointSettings = "Hide endpoint settings",
            endpointPresetBase = "Base",
            endpointPresetIntensive = "Intensive",
            endpointPresetCustom = "Other",
            intensiveCampusMoscow = "Moscow",
            intensiveCampusNovosibirsk = "Novosibirsk",
            intensiveCampusKazan = "Kazan",
            intensiveCampusOther = "Other campus",
            endpointOtherCampusPlaceholder = "https://ekb-rocket.21-school.ru",
            endpointCustomHint = "Where to find it? Sign in to the campus Rocket.Chat in a browser and copy the address from the address bar, for example rocket.21-school.ru. Or open Rocket.Chat mobile settings: the address is shown in Server.",
            endpointViewBrowserExample = "Browser example",
            endpointViewMobileExample = "App example",
            actionRefreshNow = "Refresh QR",
            actionSave = "Save",
            actionClearSaved = "Clear saved data",
            actionShowToken = "Show",
            actionHideToken = "Hide",
            connectionChecking = "Checking…",
            errorEndpointHttps = "Endpoint must start with https://",
            errorTokenRequired = "Token is required.",
            errorUserIdRequired = "User Id is required.",
            errorConnectionCheckRequired = "Run connection check successfully before finishing setup.",
            infoSettingsSaved = "Settings saved.",
            infoWizardDone = "Wizard completed, settings are active.",
            infoQrRefreshed = "QR code refreshed.",
            infoRefreshShortCooldown = "Wait a few seconds before requesting QR again.",
            statusFreshHeadline = "QR is active",
            statusRefreshingHeadline = "Refreshing QR",
            statusNeedsRefreshHeadline = "Sync attention required",
            statusMissingHeadline = "QR has not been loaded",
            statusTitle = "Status",
            statusStored = "Stored credentials",
            statusRefreshInProgress = "Refresh in progress",
            statusLastError = "Last sync error",
            statusLastCheck = "Last successful action",
            statusExpiresAt = "QR expires",
            statusConnection = "Connection status",
            statusNotSet = "not set",
            statusNever = "never",
            statusUnknown = "unknown",
            statusNone = "none",
            statusYes = "yes",
            statusNo = "no",
            qrTitle = "QR preview",
            qrEmpty = "QR code has not been loaded yet.",
            connectionSectionTitle = "Connection",
            connectionSectionBody = "Manage endpoint, user Id, and token in one place.",
            actionExpand = "Expand",
            actionCollapse = "Collapse",
            widgetTitle = "doorDuck widget",
            widgetBody = "Add the QR widget to your home screen for faster access.",
            widgetAction = "Add widget",
            widgetHelpMessage = "On iPhone, add the widget from the Home Screen editor.",
            instructionTitle = "I need the Id and token",
            instructionBody = "Open the Rocket.Chat token page and create the required credentials.",
            instructionStep1 = "1. Open the Rocket.Chat tokens page using the button below (use the web version).",
            instructionStep2 = "2. Sign in. Enter your login in the “verter@student.21-school.ru” format.",
            instructionStep3 = "3. In the “Add new Personal” field, enter any text and tap “Add”.",
            instructionStep4 = "4. Enter your Rocket.Chat password to confirm.",
            instructionStep5 = "5. Copy the full text from the popup with token and user Id.",
            instructionStep6 = "6. Paste that text into the doorDuck wizard field.",
            instructionOpenLink = "Open Rocket tokens page",
            instructionViewExample = "View example (screenshot)",
            instructionHideExample = "Hide example",
            instructionWebOnly = "Only in the Rocket.Chat web version.",
            githubLinkLabel = "GitHub",
            githubOwnerLabel = "Author: jonnabin",
            iosStatusTitle = "iOS version status",
            iosStatusBody = "Credential storage, connection checks, manual QR refresh, and the iOS home-screen widget are available. Background refresh still remains Android-only.",
            tokensUrl = Defaults.rocketTokensUrl,
            githubUrl = "https://github.com/vgy789/doorDuck",
            connectionOk = "Connection successful.",
            connectionUnauthorized = "Invalid Token or Id.",
            connectionBotNotFound = "QR bot was not found on this Rocket.Chat server.",
            connectionBotUnavailable = "Bot is unavailable or inaccessible.",
            connectionNetworkError = "Network error during connection check.",
            connectionUnknownError = "No successful connection check yet.",
            syncErrorNotConfigured = "Fill in endpoint, user Id, and token before refreshing QR.",
            syncErrorUnauthorized = "QR refresh failed: invalid token or user Id.",
            syncErrorRateLimited = "QR refresh is delayed by the bot. doorDuck will retry later.",
            syncErrorNetwork = "QR refresh failed because of a network error.",
            syncErrorBotInvalid = "QR refresh failed because the bot response was invalid.",
            syncErrorImageDownload = "QR refresh failed because the image could not be decoded.",
            syncErrorUnknown = "QR refresh has not been completed yet.",
            credentialsBlobLabel = "Text from Rocket.Chat popup",
            detectedCredentialsTitle = "Detected values",
            detectedUserIdValue = "User Id: %s",
            detectedTokenValue = "Token: %s",
            statusNotFound = "not found",
            errorCredentialsBlobRequired = "Paste the text from the popup with token and user Id.",
        )

        private fun russian() = SharedStrings(
            loading = "Загрузка doorDuck…",
            appTitle = "doorDuck для iOS",
            appSubtitle = "На iOS уже доступны настройка, проверка токена и ручное обновление QR.",
            wizardTitle = "Мастер настройки doorDuck",
            welcomeTitle = "Приветствие",
            welcomeBody = "Привет! Я doorDuck. Я отображаю рабочий QR-виджет входа в кампус на рабочем столе.",
            credentialsTitle = "Вставь текст из окна Rocket.Chat",
            credentialsHint = "Открой страницу токенов Rocket.Chat, создай новый Personal Access Token, скопируй весь текст из всплывающего окна и вставь его сюда.",
            endpointTitle = "На каком ты этапе?",
            connectionHint = "Перед завершением настройки проверь соединение с Rocket.Chat. Обязательно нажми Ok в окне создания токена Rocket.Chat.",
            doneTitle = "Настройка завершена",
            doneBody = "Настройки сохранены в iOS-версии. Позже мастер можно снова открыть из экрана настроек.",
            homeTitle = "doorDuck",
            homeSubtitle = "Текущее состояние QR и ручное обновление.",
            settingsTitle = "Настройки doorDuck",
            endpointLabel = "Адрес Rocket.Chat",
            userIdLabel = "User Id Rocket.Chat",
            tokenLabel = "X-Auth-Token",
            actionStart = "Начать",
            actionNext = "Далее",
            actionFinish = "Завершить настройку",
            actionOpenApp = "Открыть приложение",
            actionOpenSettings = "Открыть настройки",
            actionCheckConnection = "Проверить подключение",
            actionShowEndpointSettings = "Показать настройки endpoint",
            actionHideEndpointSettings = "Скрыть настройки endpoint",
            endpointPresetBase = "Основа",
            endpointPresetIntensive = "Интенсив",
            endpointPresetCustom = "Другое",
            intensiveCampusMoscow = "Москва",
            intensiveCampusNovosibirsk = "Новосибирск",
            intensiveCampusKazan = "Казань",
            intensiveCampusOther = "Другой кампус",
            endpointOtherCampusPlaceholder = "https://ekb-rocket.21-school.ru",
            endpointCustomHint = "Где найти? Войди в Rocket.Chat кампуса через браузер и скопируй полный адрес из строки, например rocket.21-school.ru. Или открой в мобильном приложении Rocket.Chat настройки: адрес указан в пункте «Сервер».",
            endpointViewBrowserExample = "Пример в браузере",
            endpointViewMobileExample = "Пример в приложении",
            actionRefreshNow = "Обновить QR",
            actionSave = "Сохранить",
            actionClearSaved = "Очистить сохранённые данные",
            actionShowToken = "Показать",
            actionHideToken = "Скрыть",
            connectionChecking = "Проверяем…",
            errorEndpointHttps = "Адрес API должен начинаться с https://",
            errorTokenRequired = "Token обязателен.",
            errorUserIdRequired = "Id обязателен.",
            errorConnectionCheckRequired = "Перед завершением нужно успешно выполнить проверку подключения.",
            infoSettingsSaved = "Настройки сохранены.",
            infoWizardDone = "Мастер завершён, настройки активны.",
            infoQrRefreshed = "QR-код обновлён.",
            infoRefreshShortCooldown = "Подожди несколько секунд перед новым запросом QR.",
            statusFreshHeadline = "QR актуален",
            statusRefreshingHeadline = "Обновляем QR",
            statusNeedsRefreshHeadline = "Синхронизации нужно внимание",
            statusMissingHeadline = "QR ещё не загружен",
            statusTitle = "Статус",
            statusStored = "Сохранённые данные",
            statusRefreshInProgress = "Обновление выполняется",
            statusLastError = "Последняя ошибка синхронизации",
            statusLastCheck = "Последнее успешное действие",
            statusExpiresAt = "QR истекает",
            statusConnection = "Статус подключения",
            statusNotSet = "не задано",
            statusNever = "никогда",
            statusUnknown = "неизвестно",
            statusNone = "нет",
            statusYes = "да",
            statusNo = "нет",
            qrTitle = "Предпросмотр QR",
            qrEmpty = "QR-код ещё не загружен.",
            connectionSectionTitle = "Подключение",
            connectionSectionBody = "Управляй адресом API, Id и токеном в одном месте.",
            actionExpand = "Развернуть",
            actionCollapse = "Свернуть",
            widgetTitle = "Виджет doorDuck",
            widgetBody = "Добавь QR-виджет на рабочий стол для быстрого доступа.",
            widgetAction = "Добавить виджет",
            widgetHelpMessage = "На iPhone виджет добавляется через режим редактирования экрана Домой.",
            instructionTitle = "Мне нужны Id и Token",
            instructionBody = "Только в WEB-версии Rocket.Chat",
            instructionStep1 = "1. Открой страницу токенов Rocket.Chat по кнопке ниже (нужна именно WEB-версия).",
            instructionStep2 = "2. Авторизуйся. Введи логин в формате «verter@student.21-school.ru».",
            instructionStep3 = "3. В поле «Add new Personal» введи любой текст и нажми «Add».",
            instructionStep4 = "4. Для подтверждения введи пароль от Rocket.Chat.",
            instructionStep5 = "5. Скопируй весь текст из всплывающего окна с Token и Id.",
            instructionStep6 = "6. Вставь этот текст в поле мастера doorDuck.",
            instructionOpenLink = "Открыть страницу токенов Rocket",
            instructionViewExample = "Посмотреть пример (скриншот)",
            instructionHideExample = "Скрыть пример",
            instructionWebOnly = "Только в WEB-версии Rocket.Chat.",
            githubLinkLabel = "GitHub",
            githubOwnerLabel = "Author: jonnabin",
            iosStatusTitle = "Состояние iOS-версии",
            iosStatusBody = "На iOS уже работают сохранение учётных данных, проверка подключения, ручное обновление QR и домашний виджет. Фоновое обновление пока остаётся только в Android-версии.",
            tokensUrl = Defaults.rocketTokensUrl,
            githubUrl = "https://github.com/vgy789/doorDuck",
            connectionOk = "Подключение успешно.",
            connectionUnauthorized = "Неверный токен или Id.",
            connectionBotNotFound = "На этом сервере Rocket.Chat не найден бот для QR.",
            connectionBotUnavailable = "Бот недоступен или к нему нет доступа.",
            connectionNetworkError = "Сетевая ошибка во время проверки подключения.",
            connectionUnknownError = "Успешная проверка подключения ещё не выполнялась.",
            syncErrorNotConfigured = "Перед обновлением QR заполни адрес API, user Id и токен.",
            syncErrorUnauthorized = "Не удалось обновить QR: неверный токен или Id.",
            syncErrorRateLimited = "Бот попросил подождать перед следующим обновлением QR. doorDuck повторит позже.",
            syncErrorNetwork = "Не удалось обновить QR из-за сетевой ошибки.",
            syncErrorBotInvalid = "Не удалось обновить QR: бот вернул некорректный ответ.",
            syncErrorImageDownload = "Не удалось обновить QR: изображение не удалось декодировать.",
            syncErrorUnknown = "Обновление QR ещё не выполнялось.",
            credentialsBlobLabel = "Текст из окна Rocket.Chat",
            detectedCredentialsTitle = "Найденные данные",
            detectedUserIdValue = "User Id: %s",
            detectedTokenValue = "Token: %s",
            statusNotFound = "не найдено",
            errorCredentialsBlobRequired = "Вставь текст из окна с Token и Id.",
        )
    }
}
