package io.github.vgy789.doorDuck.shared

import io.github.vgy789.doorDuck.model.ConnectionCheckResult
import io.github.vgy789.doorDuck.model.SyncError

internal data class SharedStrings(
    val loading: String,
    val appTitle: String,
    val appSubtitle: String,
    val wizardTitle: String,
    val welcomeTitle: String,
    val welcomeBody: String,
    val userIdTitle: String,
    val userIdHint: String,
    val tokenTitle: String,
    val tokenHint: String,
    val endpointTitle: String,
    val connectionHint: String,
    val doneTitle: String,
    val doneBody: String,
    val homeTitle: String,
    val homeSubtitle: String,
    val settingsTitle: String,
    val endpointLabel: String,
    val userIdLabel: String,
    val tokenLabel: String,
    val actionStart: String,
    val actionNext: String,
    val actionBack: String,
    val actionFinish: String,
    val actionOpenApp: String,
    val actionOpenSettings: String,
    val actionBackToHome: String,
    val actionRunWizard: String,
    val actionCheckConnection: String,
    val actionRefreshNow: String,
    val actionSave: String,
    val actionClearSaved: String,
    val actionShowToken: String,
    val actionHideToken: String,
    val connectionChecking: String,
    val errorEndpointHttps: String,
    val errorTokenRequired: String,
    val errorUserIdRequired: String,
    val errorConnectionCheckRequired: String,
    val infoSettingsSaved: String,
    val infoWizardDone: String,
    val infoQrRefreshed: String,
    val statusFreshHeadline: String,
    val statusRefreshingHeadline: String,
    val statusNeedsRefreshHeadline: String,
    val statusMissingHeadline: String,
    val statusTitle: String,
    val statusStored: String,
    val statusRefreshInProgress: String,
    val statusLastError: String,
    val statusLastCheck: String,
    val statusExpiresAt: String,
    val statusConnection: String,
    val statusNotSet: String,
    val statusNever: String,
    val statusUnknown: String,
    val statusNone: String,
    val statusYes: String,
    val statusNo: String,
    val qrTitle: String,
    val qrEmpty: String,
    val connectionSectionTitle: String,
    val connectionSectionBody: String,
    val actionExpand: String,
    val actionCollapse: String,
    val widgetTitle: String,
    val widgetBody: String,
    val widgetAction: String,
    val widgetHelpMessage: String,
    val instructionTitle: String,
    val instructionBody: String,
    val instructionStep1: String,
    val instructionStep2: String,
    val instructionStep3: String,
    val instructionStep4: String,
    val instructionStep5: String,
    val instructionOpenLink: String,
    val githubLinkLabel: String,
    val githubOwnerLabel: String,
    val iosStatusTitle: String,
    val iosStatusBody: String,
    val tokensUrl: String,
    val githubUrl: String,
    val connectionOk: String,
    val connectionUnauthorized: String,
    val connectionBotUnavailable: String,
    val connectionNetworkError: String,
    val connectionUnknownError: String,
    val syncErrorNotConfigured: String,
    val syncErrorUnauthorized: String,
    val syncErrorNetwork: String,
    val syncErrorBotInvalid: String,
    val syncErrorImageDownload: String,
    val syncErrorUnknown: String,
) {
    fun connectionMessage(result: ConnectionCheckResult?): String {
        return when (result) {
            ConnectionCheckResult.SUCCESS -> connectionOk
            ConnectionCheckResult.UNAUTHORIZED -> connectionUnauthorized
            ConnectionCheckResult.BOT_UNAVAILABLE -> connectionBotUnavailable
            ConnectionCheckResult.NETWORK_ERROR -> connectionNetworkError
            ConnectionCheckResult.UNKNOWN, null -> connectionUnknownError
        }
    }

    fun syncErrorMessage(error: SyncError?): String {
        return when (error) {
            SyncError.NOT_CONFIGURED -> syncErrorNotConfigured
            SyncError.UNAUTHORIZED -> syncErrorUnauthorized
            SyncError.NETWORK -> syncErrorNetwork
            SyncError.BOT_RESPONSE_INVALID -> syncErrorBotInvalid
            SyncError.IMAGE_DOWNLOAD_FAILED -> syncErrorImageDownload
            SyncError.UNKNOWN, null -> syncErrorUnknown
        }
    }

    companion object {
        fun forLanguage(languageCode: String): SharedStrings {
            return if (languageCode.lowercase().startsWith("ru")) russian() else english()
        }

        private fun english() = SharedStrings(
            loading = "Loading doorDuck…",
            appTitle = "doorDuck for iOS",
            appSubtitle = "Setup, token verification, and manual QR refresh are available on iOS.",
            wizardTitle = "doorDuck Setup",
            welcomeTitle = "Welcome",
            welcomeBody = "Hi! I am doorDuck. I keep your campus QR widget active on the home screen.",
            userIdTitle = "Rocket.Chat user ID",
            userIdHint = "Enter your Rocket.Chat user ID.",
            tokenTitle = "Personal access token",
            tokenHint = "Enter your X-Auth-Token.",
            endpointTitle = "Connection check",
            connectionHint = "Check connection with Rocket.Chat before finishing setup.",
            doneTitle = "Configuration complete",
            doneBody = "Settings are stored on this iPhone simulator. You can reopen the wizard later from settings.",
            homeTitle = "doorDuck",
            homeSubtitle = "Your current QR state and manual refresh controls.",
            settingsTitle = "doorDuck Settings",
            endpointLabel = "Rocket.Chat API endpoint",
            userIdLabel = "Rocket.Chat user ID",
            tokenLabel = "X-Auth-Token",
            actionStart = "Start",
            actionNext = "Next",
            actionBack = "Back",
            actionFinish = "Finish setup",
            actionOpenApp = "Open app",
            actionOpenSettings = "Open settings",
            actionBackToHome = "Back to app",
            actionRunWizard = "Run wizard",
            actionCheckConnection = "Check connection",
            actionRefreshNow = "Refresh QR",
            actionSave = "Save",
            actionClearSaved = "Clear saved data",
            actionShowToken = "Show",
            actionHideToken = "Hide",
            connectionChecking = "Checking…",
            errorEndpointHttps = "Endpoint must start with https://",
            errorTokenRequired = "Token is required.",
            errorUserIdRequired = "User ID is required.",
            errorConnectionCheckRequired = "Run connection check successfully before finishing setup.",
            infoSettingsSaved = "Settings saved.",
            infoWizardDone = "Wizard completed, settings are active.",
            infoQrRefreshed = "QR code refreshed.",
            statusFreshHeadline = "QR is active",
            statusRefreshingHeadline = "Refreshing QR",
            statusNeedsRefreshHeadline = "Sync attention required",
            statusMissingHeadline = "QR has not been loaded",
            statusTitle = "Status",
            statusStored = "Stored credentials",
            statusRefreshInProgress = "Refresh in progress",
            statusLastError = "Last sync error",
            statusLastCheck = "Last successful action",
            statusExpiresAt = "QR expires",
            statusConnection = "Connection status",
            statusNotSet = "not set",
            statusNever = "never",
            statusUnknown = "unknown",
            statusNone = "none",
            statusYes = "yes",
            statusNo = "no",
            qrTitle = "QR preview",
            qrEmpty = "QR code has not been loaded yet.",
            connectionSectionTitle = "Connection",
            connectionSectionBody = "Manage endpoint, user ID, and token in one place.",
            actionExpand = "Expand",
            actionCollapse = "Collapse",
            widgetTitle = "doorDuck widget",
            widgetBody = "Add the QR widget to your home screen for faster access.",
            widgetAction = "Add widget",
            widgetHelpMessage = "On iPhone, add the widget from the Home Screen editor.",
            instructionTitle = "How to get ID and token",
            instructionBody = "Open the Rocket.Chat token page and create the required credentials.",
            instructionStep1 = "1. Open Rocket.Chat in a browser: Avatar -> Settings -> Personal Access Tokens.",
            instructionStep2 = "2. Enter any token name.",
            instructionStep3 = "3. In the dropdown next to Add, choose \"Ignore Two-Factor Authentication\".",
            instructionStep4 = "4. Click Add and copy the generated user ID and token.",
            instructionStep5 = "5. Do not delete the token, doorDuck uses it for connection checks and QR refresh.",
            instructionOpenLink = "Open Rocket tokens page",
            githubLinkLabel = "GitHub",
            githubOwnerLabel = "s21 login: jonnabin",
            iosStatusTitle = "iOS version status",
            iosStatusBody = "Credential storage, connection checks, manual QR refresh, and the iOS home-screen widget are available. Background refresh still remains Android-only.",
            tokensUrl = "https://rocketchat-student.21-school.ru/account/tokens",
            githubUrl = "https://github.com/vgy789/doorDuck",
            connectionOk = "Connection successful.",
            connectionUnauthorized = "Invalid token or user ID.",
            connectionBotUnavailable = "Bot is unavailable or inaccessible.",
            connectionNetworkError = "Network error during connection check.",
            connectionUnknownError = "No successful connection check yet.",
            syncErrorNotConfigured = "Fill in endpoint, user ID, and token before refreshing QR.",
            syncErrorUnauthorized = "QR refresh failed: invalid token or user ID.",
            syncErrorNetwork = "QR refresh failed because of a network error.",
            syncErrorBotInvalid = "QR refresh failed because the bot response was invalid.",
            syncErrorImageDownload = "QR refresh failed because the image could not be decoded.",
            syncErrorUnknown = "QR refresh has not been completed yet.",
        )

        private fun russian() = SharedStrings(
            loading = "Загрузка doorDuck…",
            appTitle = "doorDuck для iOS",
            appSubtitle = "На iOS уже доступны настройка, проверка токена и ручное обновление QR.",
            wizardTitle = "Мастер настройки doorDuck",
            welcomeTitle = "Добро пожаловать",
            welcomeBody = "Привет! Я doorDuck. Я поддерживаю рабочий QR-виджет входа в кампус на рабочем столе.",
            userIdTitle = "Идентификатор пользователя Rocket.Chat",
            userIdHint = "Введи свой Rocket.Chat user ID.",
            tokenTitle = "Персональный токен",
            tokenHint = "Введи свой X-Auth-Token.",
            endpointTitle = "Проверка подключения",
            connectionHint = "Перед завершением настройки проверь соединение с Rocket.Chat. Обязательно нажми Ok в окне создания токена Rocket.Chat.",
            doneTitle = "Настройка завершена",
            doneBody = "Настройки сохранены в iOS-версии. Позже мастер можно снова открыть из экрана настроек.",
            homeTitle = "doorDuck",
            homeSubtitle = "Текущее состояние QR и ручное обновление.",
            settingsTitle = "Настройки doorDuck",
            endpointLabel = "Адрес Rocket.Chat API",
            userIdLabel = "User ID Rocket.Chat",
            tokenLabel = "X-Auth-Token",
            actionStart = "Начать",
            actionNext = "Далее",
            actionBack = "Назад",
            actionFinish = "Завершить настройку",
            actionOpenApp = "Открыть приложение",
            actionOpenSettings = "Открыть настройки",
            actionBackToHome = "Назад в приложение",
            actionRunWizard = "Запустить мастер",
            actionCheckConnection = "Проверить подключение",
            actionRefreshNow = "Обновить QR",
            actionSave = "Сохранить",
            actionClearSaved = "Очистить сохранённые данные",
            actionShowToken = "Показать",
            actionHideToken = "Скрыть",
            connectionChecking = "Проверяем…",
            errorEndpointHttps = "Адрес API должен начинаться с https://",
            errorTokenRequired = "Токен обязателен.",
            errorUserIdRequired = "User ID обязателен.",
            errorConnectionCheckRequired = "Перед завершением нужно успешно выполнить проверку подключения.",
            infoSettingsSaved = "Настройки сохранены.",
            infoWizardDone = "Мастер завершён, настройки активны.",
            infoQrRefreshed = "QR-код обновлён.",
            statusFreshHeadline = "QR актуален",
            statusRefreshingHeadline = "Обновляем QR",
            statusNeedsRefreshHeadline = "Синхронизации нужно внимание",
            statusMissingHeadline = "QR ещё не загружен",
            statusTitle = "Статус",
            statusStored = "Сохранённые данные",
            statusRefreshInProgress = "Обновление выполняется",
            statusLastError = "Последняя ошибка синхронизации",
            statusLastCheck = "Последнее успешное действие",
            statusExpiresAt = "QR истекает",
            statusConnection = "Статус подключения",
            statusNotSet = "не задано",
            statusNever = "никогда",
            statusUnknown = "неизвестно",
            statusNone = "нет",
            statusYes = "да",
            statusNo = "нет",
            qrTitle = "Предпросмотр QR",
            qrEmpty = "QR-код ещё не загружен.",
            connectionSectionTitle = "Подключение",
            connectionSectionBody = "Управляй адресом API, user ID и токеном в одном месте.",
            actionExpand = "Развернуть",
            actionCollapse = "Свернуть",
            widgetTitle = "Виджет doorDuck",
            widgetBody = "Добавь QR-виджет на рабочий стол для быстрого доступа.",
            widgetAction = "Добавить виджет",
            widgetHelpMessage = "На iPhone виджет добавляется через режим редактирования экрана Домой.",
            instructionTitle = "Как получить ID и токен",
            instructionBody = "Открой страницу токенов Rocket.Chat и создай нужные данные.",
            instructionStep1 = "1. Открой Rocket.Chat в браузере: Avatar -> Settings -> Personal Access Tokens.",
            instructionStep2 = "2. Введи любое имя токена.",
            instructionStep3 = "3. В выпадающем меню рядом с Add выбери \"Ignore Two-Factor Authentication\".",
            instructionStep4 = "4. Нажми Add и скопируй сгенерированные user ID и token.",
            instructionStep5 = "5. Не удаляй токен, doorDuck использует его для проверки подключения и обновления QR.",
            instructionOpenLink = "Открыть страницу токенов Rocket",
            githubLinkLabel = "GitHub",
            githubOwnerLabel = "s21 login: jonnabin",
            iosStatusTitle = "Состояние iOS-версии",
            iosStatusBody = "На iOS уже работают сохранение учётных данных, проверка подключения, ручное обновление QR и домашний виджет. Фоновое обновление пока остаётся только в Android-версии.",
            tokensUrl = "https://rocketchat-student.21-school.ru/account/tokens",
            githubUrl = "https://github.com/vgy789/doorDuck",
            connectionOk = "Подключение успешно.",
            connectionUnauthorized = "Неверный токен или user ID.",
            connectionBotUnavailable = "Бот недоступен или к нему нет доступа.",
            connectionNetworkError = "Сетевая ошибка во время проверки подключения.",
            connectionUnknownError = "Успешная проверка подключения ещё не выполнялась.",
            syncErrorNotConfigured = "Перед обновлением QR заполни адрес API, user ID и токен.",
            syncErrorUnauthorized = "Не удалось обновить QR: неверный токен или user ID.",
            syncErrorNetwork = "Не удалось обновить QR из-за сетевой ошибки.",
            syncErrorBotInvalid = "Не удалось обновить QR: бот вернул некорректный ответ.",
            syncErrorImageDownload = "Не удалось обновить QR: изображение не удалось декодировать.",
            syncErrorUnknown = "Обновление QR ещё не выполнялось.",
        )
    }
}
